### ISSUE TITLE
Handle `licenses` as an array with a single object

### ISSUE THREAD

**Issue by bnb** [cutenode/liblice#1]
I found a super interesting edge case from a 6 year old module that is widely used, and likely not going to update:

```json
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/Gozala/enchain/License.md"
    }
  ],
```

Adding logic to handle this in [parseLicense.js](https://github.com/cutenode/liblice/blob/master/lib/parseLicense.js) would be super helpful.

**Comment by bnb** [comment]
Found a couple more examples:

```json
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/jryans/timers-browserify/blob/master/LICENSE.md"
    }
  ],
```

```json
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/tkellen/node-rechoir/blob/master/LICENSE"
    }
  ],
```

**Comment by bnb** [comment]
Also, when addressed we should make sure that test coverage is properly added.

**Comment by jonchurch** [comment]
Looks like this was handled in https://github.com/cutenode/liblice/commit/17455f2b0e93bef2e443dca03c2555ebc3ae46aa

**Comment by bnb** [comment]
Addressed 👍
